## Documentation: http://docs.travis-ci.com/user/languages/julia/

sudo: required
language: julia
services: docker
julia:
  - 1.1
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("Perla1")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Perla1")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

before_deploy:
- export TRAVIS_TAG=${TRAVIS_TAG:-dev}
- git tag $TRAVIS_TAG --force
# tex stuff
- docker pull dxjoke/tectonic-docker
- docker run --mount src=$TRAVIS_BUILD_DIR/docs/tex,target=/usr/src/tex,type=bind dxjoke/tectonic-docker
  /bin/sh -c "./generate_tex.sh"
# weave stuff
- docker pull quantecon/julia-weave
- docker run -it --rm -v "$TRAVIS_BUILD_DIR/docs/notebooks":/usr/myapp -w /usr/myapp quantecon/julia-weave julia generate_notebooks.jl
deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file_glob: true
  file:
  - $TRAVIS_BUILD_DIR/docs/tex/*.pdf
  - $TRAVIS_BUILD_DIR/docs/notebooks/*.ipynb
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
